// <auto-generated />
namespace WebLtic.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class TaiXe : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TaiXe));
        
        string IMigrationMetadata.Id
        {
            get { return "202303020148558_TaiXe"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
